In [1]:
import numpy as np

In [3]:
vec = np.arange(1,6)
vec

array([1, 2, 3, 4, 5])

### Karsilastirma Operatoru Ile Kullanim

In [6]:
vec < 3 # arrayi bir karşılaştırma operatoru ile kullandıgımızda onu sağlayan indexleri true diğerlerini false alır

array([ True,  True, False, False, False])

In [10]:
vec[vec < 3] # bu listeyi fancy index mantıgı ile verirsek sadece true olan indexleri bize geri döndürür

array([1, 2])

In [13]:
condition = vec >= 3 # bu kullanım bize liste döndürdüğü için değişken içerisinde de kullanabiliriz
vec[condition]

array([3, 4, 5])

In [14]:
vec

array([1, 2, 3, 4, 5])

In [15]:
vec * 2  # Bütün Elemanları 2 ile çarpar

array([ 2,  4,  6,  8, 10])

In [16]:
vec / 5 # bütün elemanları 5 ile böler

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [18]:
vec ** 2 # hepsinin karesini alır

array([ 1,  4,  9, 16, 25])