In [1]:
import numpy as np
arr = np.random.randint(0,10,10)
arr

array([6, 0, 1, 8, 8, 6, 5, 2, 6, 6])

In [2]:
arr[0] # index ile elemana erişim

6

### 2 Boyutlu Arraylarda İndex İle Erişim

In [3]:
arr = np.random.randint(0,10,(3,5))
arr

array([[7, 7, 7, 3, 4],
       [2, 4, 1, 4, 4],
       [1, 9, 8, 3, 3]])

In [4]:
arr[0][2] = 31

### Normalde numpy arrayleri oluşturuyorken sayılardan bir tanesi bile floatsa bütün dizi float olurdu
### falat var olan bir int numpy arraye float atarsak onu int olarak algılar

In [5]:
arr[0][2] = 2.2
arr

array([[7, 7, 2, 3, 4],
       [2, 4, 1, 4, 4],
       [1, 9, 8, 3, 3]])