In [22]:
import numpy as np

In [23]:
arr = np.random.randint(0,10,(5,5))
arr

array([[6, 9, 6, 3, 0],
       [7, 2, 8, 1, 9],
       [2, 1, 2, 1, 8],
       [5, 0, 7, 7, 9],
       [0, 5, 4, 5, 9]])

In [24]:
alt_a = arr.copy()[0:3 , 0:2]
# alt_a = arr[0:3 , 0:2].copy()
alt_a

array([[6, 9],
       [7, 2],
       [2, 1]])

In [25]:
alt_a[0,0] = 9999
alt_a[1,1] = 888
alt_a

array([[9999,    9],
       [   7,  888],
       [   2,    1]])

In [26]:
arr

array([[6, 9, 6, 3, 0],
       [7, 2, 8, 1, 9],
       [2, 1, 2, 1, 8],
       [5, 0, 7, 7, 9],
       [0, 5, 4, 5, 9]])