In [2]:
import numpy as np


In [3]:
arr = np.arange(20,30)
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### Slice Kullanımı

In [5]:
arr[0:3] # slice işleminde belirli bir aralık belirtiriz bunun için araya ' : ' konulur

array([20, 21, 22])

In [6]:
arr[:3] # 0dan 3 e kadar git

array([20, 21, 22])

In [7]:
arr[::2] # 0 dan son indexe kadar 2 şer 2şer gir (3. parametre atlama sayısıdır)

array([20, 22, 24, 26, 28])

### 2 Boyutlu Slice İşlemleri

In [8]:
new_Arr = np.random.randint(0,10,(5,5))
new_Arr

array([[4, 8, 9, 7, 4],
       [9, 9, 1, 0, 5],
       [0, 9, 8, 2, 1],
       [4, 5, 6, 9, 7],
       [8, 5, 7, 1, 9]])

In [11]:
new_Arr[:3,0:2] # virgülden önceki ilk kısım satır aralığı sonraki ksıım sütun aralığını belirler

array([[4, 8],
       [9, 9],
       [0, 9]])

In [14]:
new_Arr[0,:]

array([4, 8, 9, 7, 4])

In [16]:
new_Arr[2:,:3]

array([[0, 9, 8],
       [4, 5, 6],
       [8, 5, 7]])

In [18]:
new_Arr

array([[4, 8, 9, 7, 4],
       [9, 9, 1, 0, 5],
       [0, 9, 8, 2, 1],
       [4, 5, 6, 9, 7],
       [8, 5, 7, 1, 9]])

In [23]:
new_Arr[::,:2] # iki nokta ile bütün satırları al diyoruz ama sadece tek nokta koysakta çalışır

array([[4, 8],
       [9, 9],
       [0, 9],
       [4, 5],
       [8, 5]])