In [20]:
import numpy as np

In [21]:
vec = np.arange(0,30,3)
vec

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [22]:
[vec[1] , vec[3] , vec[5]]


[3, 9, 15]

### Fancy Index

In [23]:
index_list = [1,3,5]
vec[index_list] # fancy index ile bir listeye bir index listesi vererek o indexlerdeki verileri getirir

array([ 3,  9, 15])

### 2 Boyutlu Arraylarda Fancy Index

In [24]:
matris = np.arange(0,9).reshape(3,3)
matris

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
satir = np.array([0,1])
sutun = np.array([0,2])

In [29]:
matris[satir , sutun] # 0.satir 0. sütun ve 1.satir 2.sutun alındı

array([0, 5])

### Basit Index Ile Fancy Index

In [30]:
matris[0 , [1,2]] # burdaki satır bilgisi sadece 1 oldugu için ilk satırdaki 1 ve 2 indexteki verileri alır

array([1, 2])

### Slice ile Fancy Index

In [32]:
matris[0: , [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])