In [1]:
import numpy as np

In [2]:
v = np.arange(1,6)
v

array([1, 2, 3, 4, 5])

### Numpy Arraylarda Matematiksel İşlemler

In [3]:
v - 1 # bütün elemanlardan 1 çıkardı

array([0, 1, 2, 3, 4])

In [4]:
v * 3 # bütün elemanları 3 ile çarptı

array([ 3,  6,  9, 12, 15])

### ufunc

In [6]:
np.subtract(v , 1) # biz direkt çıkartma yapsakta arkada bu işlemler çalışır

array([0, 1, 2, 3, 4])

In [7]:
np.add(v,3) # arkada çalışan toplama işlemi

array([4, 5, 6, 7, 8])

In [9]:
np.multiply(v,4) # arkada çalışan çarpma işlemi

array([ 4,  8, 12, 16, 20])

In [10]:
np.power(v,3) # arka planda karesini alır

array([  1,   8,  27,  64, 125], dtype=int32)

In [11]:
np.mod(v,2) # arkada modunu alır

array([1, 0, 1, 0, 1], dtype=int32)

In [13]:
np.absolute(np.array([-1,-2,-3])) # arkada mutlak deger alır

array([1, 2, 3])

In [16]:
print("sin =",np.sin(360))
print("cos =",np.cos(360))

sin = 0.9589157234143065
cos = -0.2836910914865273


In [18]:
np.log(v) # bütün elemanların logaritmasını alır

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [19]:
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [23]:
np.mean(v) # ortalama alır

3.0

In [24]:
np.min(v) # min degeri verir

1

In [25]:
np.sum(v) # toplamı verir

15