In [1]:
import numpy as np

## Tek Boyutlu Arraylarda Sıralama

In [9]:
x = np.array([4,2,5,1,3])
x

array([4, 2, 5, 1, 3])

In [11]:
np.sort(x) # numpy içerisinden çağırdığımız için içerik değişmez

array([1, 2, 3, 4, 5])

In [13]:
x.sort() # değişken üzerinden çağırdığımız için içerik değişir
x

array([1, 2, 3, 4, 5])

## 2 Boyutlu Arraylarda Sıralama

In [30]:
m = np.random.normal(20 , 5 , (3,3))
m

array([[21.14411115, 16.07417858, 19.84408788],
       [12.12123231, 13.50293483, 17.67317429],
       [32.31406336, 19.84173049, 21.12248346]])

In [31]:
np.sort(m , axis=1) # bütün satırları küçükten büyüğe doğru sıraladı

array([[16.07417858, 19.84408788, 21.14411115],
       [12.12123231, 13.50293483, 17.67317429],
       [19.84173049, 21.12248346, 32.31406336]])

In [33]:
np.sort(m , axis=0) # bütün sütunları küçükten büyüğe doğru sıraladı

array([[12.12123231, 13.50293483, 17.67317429],
       [21.14411115, 16.07417858, 19.84408788],
       [32.31406336, 19.84173049, 21.12248346]])