In [7]:
import numpy as np

### Numpy Array oluşturma

In [6]:
np_arr = np.array([1,2,3]) # içerisine verdiğimiz 
print(np_arr)

[1 2 3]


### Numpy Arraylarda tip

In [7]:
np_arr = np.array([1,2,3,4] , dtype="float32") # dtype veri tipini belirler
type(np_arr)

numpy.ndarray

### Sıfırdan Array Oluşturma

In [8]:
np.zeros(10 , dtype="int") # 0 lardan oluşan bir array oluşturur

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones((3,5) , dtype="int") # 1 lerden oluşan bir array oluşturur
                             # tuple olarak verdiğimiz değerler arrayin kaça kaçlık oldgunu belirtir                                      

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full((3,5) , 3) # verdiğimiz tuple ile shape i belirledik ve içine 2. parametre ile ne koyacagımızı verdik

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [9]:
print(np.arange(0,31),"\n") # 0dan başlar 1er 1er atlayarak 31 e kadar gider
print(np.arange(0,31,3)) # 0 dan başlayıp 3 er 3er atlayarak 31 e kadar olan sayıları belirtir
                         # 3.parametre atlanacak sayıyı belirtir

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30] 

[ 0  3  6  9 12 15 18 21 24 27 30]


In [12]:
np.linspace(0,1,10) # 0 ile 1 arasını 10a bölerek 10 tane değer oluşturur

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
np.random.normal(10 , 4 , (3,5)) # bu fonksiyon ilk parametre ort ikinci standart sapma 3 ise boyut
                                 # bize girilenm ort ve standart sapmaya sahip girdiğimiz boyutta matris oluşturur

array([[14.24836714, 13.11462675,  1.35663732,  2.42773026, 10.03310744],
       [11.78707885, 11.08192188,  4.20211304,  8.97298433,  5.46683814],
       [10.18040216,  9.7997202 ,  7.07545575, 13.82489095,  6.71068766]])

In [14]:
np.random.randint(0,10,3) # 3x3 lük 0,10 arasında rastgele matris oluşturur

array([72, 31, 93])

In [17]:
np.random.uniform(5,100,5) # 5 ile 100 arasında 5 tane float satı oluştrurur

array([36.71094482, 73.73082927, 59.12502049, 59.39777737, 88.2597789 ])