In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,99,99,3,2,1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [3]:
np.split(x , [3,5]) # 2 index verdik 3 e ayrıldı # verilen liste hangi indexlerden ayıracagını belirler

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [6]:
a,b,c = np.split(x , [3,5])

In [10]:
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


### vsplit(Satır Bazında Bölme)

In [17]:
new_arr = np.arange(0,16).reshape(4,4)
m,n = np.vsplit(new_arr , [2]) # vsplit fonksiyonu satır bazında böler 2 verdiğimiz için 2 ye kadar olan kısmı böldü

### hsplit(Sütun Bazında Bölme)

In [22]:
sag , sol = np.hsplit(new_arr , [2]) #hsplit fonksiyonu sütun bazında böle 2 verdiğimiz için 2.sutuna kadar olan kısmı böldü
print(new_arr)
print(sag)
print(sol)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
