In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [3]:
np.concatenate([x,y]) # 2 arrayi yan yana birleştirir

array([1, 2, 3, 4, 5, 6])

In [4]:
z = np.array([7,8,9])
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2 Boyutlu Birleştirme

In [9]:
a = np.array([[1,2,3] ,
             [4,5,6]])

b = np.array([[7,8,9],
            [10,11,12]])

In [22]:
np.concatenate([a,b] , axis=1) # axis değer default olarak 0 dır eğer axis belirtmezsek satır bazında birleştirir
                                # eğer axis 1 olursa sütun bazında birleştirir

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [23]:
print(f"vstack =>\n{np.vstack((a,b))}\n") # vsatack concatenate gibi calısır fakat burda axis belirtmeye gerek yok axis = 0
print(f"hstack =>\n{np.hstack((a,b))}") # hsatack concatenate gibi calısır fakat burda axis belirtmeye gerek yok axis = 1

vstack =>
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

hstack =>
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
